name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: gulp scripts
    - run: npm run eslint
  
  images:
    steps:
      - uses: actions/checkout@v2

      - name: Check image files
        uses: tj-actions/verify-changed-files@v11.1
        id: verify-changed-files
        with:
          files: |
             **/*.png
             **/*.jpeg
             **/*.jpg

      - name: Run step only when images change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Detected image file changes, please ensure all images have been minified with something like https://tinypng.com/ !"
